version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  wolfram-language-paclet-test:
    docker:
      - image: maxitg/set-replace-wl-ci:12.1.1
        auth:
          username: maxitg
          password: $DOCKERHUB_PASSWORD
    parallelism: 4

    steps:
      - checkout

      - run:
          name: Build
          command: ./build.wls

      - store_artifacts:
          path: ./LibraryResources/

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Copy libraries from other platforms
          command: cp -r /tmp/workspace/* ./LibraryResources/

      - run:
          name: Install
          command: ./install.wls

      - store_artifacts:
          path: ./BuiltPaclets/

      - run:
          name: Reinstall
          command: ./install.wls

      - run:
          name: Test
          command: |
            testsToRun=$(circleci tests glob "Tests/*.wlt" \
              | circleci tests split --total=4 --split-by=filesize \
              | sed "s/\.wlt//" \
              | sed "s/Tests\///")
            ./.circleci/test.sh $testsToRun

  cpp-test:
    docker:
      - image: alpine:3.12.1
        auth:
          username: maxitg
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - run:
          name: Install Required Tools
          command: |
            apk add --no-cache \
              bash boost-dev boost-static git g++ make cmake \
              clang py-pip shellcheck shfmt grep npm
            pip install cpplint
            npm install -g markdownlint-cli

      - run:
          name: Lint
          command: |
            set +eo pipefail
            ./lint.sh
            if [ $? -ne 0 ]
            then
              echo "Please run scripts/install_git_hooks.sh to detect linting issues before git push."
              exit 1
            fi

      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake .. -DPOST_TAG_SYSTEM_BUILD_TESTING=ON \
                     -DPOST_TAG_SYSTEM_BUILD_CLI=ON \
                     -DPOST_TAG_SYSTEM_ENABLE_ALLWARNINGS=ON
            cmake --build .

      - run:
          name: Test
          command: ./libPostTagSystemTest.sh

      - store_test_results:
          path: TestResults

  cpp-32-test:
    docker:
      - image: i386/alpine:3.12.1
        auth:
          username: maxitg
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - run:
          name: Install Required Tools
          command: apk add --no-cache bash boost-dev boost-static git g++ make cmake

      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake .. -DPOST_TAG_SYSTEM_BUILD_TESTING=ON \
                     -DPOST_TAG_SYSTEM_BUILD_CLI=ON \
                     -DPOST_TAG_SYSTEM_ENABLE_ALLWARNINGS=ON
            cmake --build .

      - run:
          name: Test
          command: ./libPostTagSystemTest.sh

      - store_test_results:
          path: TestResults

  macos-build:
    macos:
      xcode: 12.2.0

    steps:
      - checkout

      - run:
          name: Install CMake
          command: |
            cmakeURL="https://github.com/Kitware/CMake/releases/download/v3.18.6/cmake-3.18.6-Darwin-x86_64.tar.gz"
            curl -L --output cmake.tar.gz $cmakeURL
            tar xf cmake.tar.gz
            cmakeDir=$(ls | grep cmake-*)
            mkdir -p /usr/local/bin /usr/local/share
            cp -r $cmakeDir/CMake.app/Contents/bin/* /usr/local/bin/
            cp -r $cmakeDir/CMake.app/Contents/share/* /usr/local/share/

      - run:
          name: Build
          command: scripts/buildLibraryResources.sh

      - persist_to_workspace:
          root: LibraryResources
          paths:
            - MacOSX-x86-64

      - store_artifacts:
          path: ./LibraryResources/

  windows-build:
    executor:
      name: win/default
      shell: bash.exe

    steps:
      - checkout

      - run:
          name: Install CMake
          command: |
            cmakeURL="https://github.com/Kitware/CMake/releases/download/v3.18.6/cmake-3.18.6-win64-x64.zip"
            curl -L --output cmake.zip $cmakeURL
            unzip -q cmake.zip
            cmakeDir=$(dir -1 | findstr -i cmake-*)
            echo "export PATH=\"$(pwd)/$cmakeDir/bin:$PATH\"" >> $BASH_ENV

      - run:
          name: Install Boost headers and build libraries
          command: |
            boostURL="https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.zip"
            curl -L --output boost.zip $boostURL
            unzip -q boost.zip
            boostDir=$(dir -1 | findstr -i boost_*)
            echo "export BOOST_ROOT=\"$(pwd)/$boostDir\"" >> $BASH_ENV
            grep BOOST_ $BASH_ENV
            cd $boostDir
            ./bootstrap.bat
            ./b2 --with-program_options

      - run:
          name: Build
          command: scripts/buildLibraryResources.sh

      - persist_to_workspace:
          root: LibraryResources
          paths:
            - Windows-x86-64

      - store_artifacts:
          path: ./LibraryResources/

      - run:
          name: Build
          command: |
            mkdir -p build
            cd build
            cmake .. \
              -DPOST_TAG_SYSTEM_ENABLE_ALLWARNINGS=ON \
              -DPOST_TAG_SYSTEM_BUILD_CLI=ON \
              -DPOST_TAG_SYSTEM_CLI_STATIC_BUILD=ON \
              -DCMAKE_BUILD_TYPE=Release
            cmake --build . --config Release

      - store_artifacts:
          path: ./build/CLI/Release

workflows:
  version: 2
  build-and-test:
    jobs:
      - macos-build
      - windows-build
      - cpp-test
      - cpp-32-test
      - wolfram-language-paclet-test:
          requires:
            - macos-build
            - windows-build
